ALTER TABLE [Traffic].[PageViews]
    ADD CONSTRAINT [PageViewsPK] PRIMARY KEY CLUSTERED ([PvId] ASC, [PvDate] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [ByMonthPS] ([PvDate]);

