ALTER TABLE [dbo].[Votes]
    ADD CONSTRAINT [VotesPK] PRIMARY KEY CLUSTERED ([VoteId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

